# Generated by Django 5.0.4 on 2026-03-27 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'charge_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('mode', models.CharField(choices=[('sea_fcl', 'Sea – FCL'), ('sea_lcl', 'Sea – LCL'), ('air', 'Air'), ('road', 'Road'), ('rail', 'Rail'), ('multimodal', 'Multimodal')], max_length=15)),
                ('incoterms', models.CharField(blank=True, help_text='EXW, FOB, CIF, DDP …', max_length=10)),
                ('cargo_type', models.CharField(blank=True, max_length=80)),
                ('cargo_ready_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to Shipment')], db_index=True, default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, help_text='CBM, KG, container, lot …', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quotations.chargetype')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'db_table': 'quotation_items',
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer'], name='quotations_custome_3c961a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status'], name='quotations_status_5ae774_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='quotations_quotati_298c04_idx'),
        ),
    ]
