# Generated by Django 5.0.4 on 2026-03-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry / nature of business description', max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='legal_structure',
            field=models.CharField(blank=True, choices=[('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('pvt_ltd', 'Private Limited'), ('llp', 'LLP'), ('other', 'Other')], help_text='Legal form of the entity (Companies Act / registration type)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='msme_registration',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipment_preferences',
            field=models.TextField(blank=True, help_text='Shipment type, trade routes, cargo types, typical volume'),
        ),
        migrations.AddField(
            model_name='customer',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(choices=[('registered', 'Registered office'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('both', 'Both')], default='both', max_length=15),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='document_type',
            field=models.CharField(choices=[('gst_certificate', 'GST Certificate'), ('pan_copy', 'PAN Copy'), ('iec_certificate', 'IEC Certificate'), ('address_proof', 'Address proof'), ('authorized_signatory_id', 'Authorized signatory ID'), ('trade_license', 'Trade License'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], max_length=30),
        ),
    ]
