# Generated by Django 5.0.4 on 2026-03-27 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('hsn_sac', models.CharField(blank=True, help_text='HSN / SAC code for GST', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'invoice_items',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('invoice_type', models.CharField(choices=[('tax_invoice', 'Tax Invoice'), ('proforma', 'Proforma Invoice'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], default='tax_invoice', max_length=20)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('sent', 'Sent'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('pdf_url', models.TextField(blank=True)),
                ('is_interstate', models.BooleanField(default=True, help_text='True=IGST, False=CGST+SGST')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
