# Generated by Django 5.0.4 on 2026-03-30 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_default_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Frontend route key, e.g. dashboard, quotation', max_length=60, unique=True)),
                ('name', models.CharField(help_text='Human-readable label shown in permission matrix', max_length=120)),
                ('module', models.CharField(blank=True, help_text='Logical grouping: core, admin, finance …', max_length=60)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'screens',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='homepage',
            field=models.CharField(blank=True, default='dashboard', help_text='Default landing screen code', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='code',
            field=models.CharField(blank=True, help_text='Short code e.g. SALES, ACCT', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_users', to='users.usergroup'),
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='users.usergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_group_memberships',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='groups_m2m',
            field=models.ManyToManyField(blank=True, related_name='memberships', through='users.UserGroupMembership', to='users.usergroup'),
        ),
        migrations.CreateModel(
            name='ScreenPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_reject', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_permissions', to='users.usergroup')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='users.screen')),
            ],
            options={
                'db_table': 'screen_permissions',
                'ordering': ['group', 'screen'],
                'unique_together': {('group', 'screen')},
            },
        ),
        migrations.CreateModel(
            name='UserScreenOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(blank=True, null=True)),
                ('can_add', models.BooleanField(blank=True, null=True)),
                ('can_edit', models.BooleanField(blank=True, null=True)),
                ('can_delete', models.BooleanField(blank=True, null=True)),
                ('can_approve', models.BooleanField(blank=True, null=True)),
                ('can_reject', models.BooleanField(blank=True, null=True)),
                ('can_export', models.BooleanField(blank=True, null=True)),
                ('can_print', models.BooleanField(blank=True, null=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='users.screen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_screen_overrides',
                'unique_together': {('user', 'screen')},
            },
        ),
    ]
