# Generated by Django 5.0.4 on 2026-03-27 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('shipping_line', 'Shipping Line'), ('airline', 'Airline'), ('trucking', 'Trucking / Road'), ('cfs', 'CFS / ICD'), ('customs_broker', 'Customs Broker'), ('surveyor', 'Surveyor'), ('warehouse', 'Warehouse'), ('other', 'Other')], max_length=20)),
                ('gst', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pan', models.CharField(blank=True, max_length=12)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, max_length=15)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_days', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payments', to='shipments.shipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_desc', models.CharField(max_length=200)),
                ('origin', models.CharField(blank=True, max_length=150)),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('unit', models.CharField(blank=True, help_text='per container / per kg / per CBM …', max_length=30)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_rates',
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['service_type', 'status'], name='vendors_service_571cab_idx'),
        ),
    ]
