# Generated by Django 5.0.4 on 2026-03-27 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(blank=True, max_length=15)),
                ('container_type', models.CharField(choices=[('20GP', "20' General Purpose"), ('40GP', "40' General Purpose"), ('40HC', "40' High Cube"), ('20RF', "20' Reefer"), ('40RF', "40' Reefer"), ('OOG', 'Out of Gauge'), ('TANK', 'Tank Container')], max_length=10)),
                ('seal_number', models.CharField(blank=True, max_length=30)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, help_text='kg', max_digits=10, null=True)),
                ('cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('packages', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'containers',
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shipment_tracking',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('mode', models.CharField(choices=[('sea_fcl', 'Sea – FCL'), ('sea_lcl', 'Sea – LCL'), ('air', 'Air'), ('road', 'Road'), ('rail', 'Rail'), ('multimodal', 'Multimodal')], max_length=15)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('port_of_loading', models.CharField(blank=True, max_length=150)),
                ('port_of_discharge', models.CharField(blank=True, max_length=150)),
                ('carrier_name', models.CharField(blank=True, max_length=100)),
                ('vessel_name', models.CharField(blank=True, max_length=100)),
                ('voyage_number', models.CharField(blank=True, max_length=50)),
                ('mbl_number', models.CharField(blank=True, help_text='Master Bill of Lading', max_length=50)),
                ('hbl_number', models.CharField(blank=True, help_text='House Bill of Lading', max_length=50)),
                ('awb_number', models.CharField(blank=True, help_text='Airway Bill (air shipments)', max_length=50)),
                ('etd', models.DateField(blank=True, help_text='Estimated Time of Departure', null=True)),
                ('eta', models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('atd', models.DateField(blank=True, help_text='Actual Time of Departure', null=True)),
                ('ata', models.DateField(blank=True, help_text='Actual Time of Arrival', null=True)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('selling_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('buying_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cargo_received', 'Cargo Received'), ('in_transit', 'In Transit'), ('at_origin_port', 'At Origin Port'), ('on_vessel', 'On Vessel'), ('at_dest_port', 'At Destination Port'), ('customs_hold', 'Customs Hold'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='booked', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='customers.customer')),
                ('quotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment', to='quotations.quotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
